### ISSUE TITLE
PyTAAADL__0_train_many_DL_models.py

### ISSUE THREAD

**Issue by davdigioia** [DonaldPG/PyTAAADL#2]
Hi Donald. thanks for your work. Now im facing this error. 
File "PyTAAADL__0_train_many_DL_models.py", line 650, in <module>
    output_incr='monthly')
  File "/home/.../PyTAAADL-master/functions/TAfunctions.py", line 1653, in generateExamples3layerGen
    forecast = forecast.reshape(forecast.shape[0],1)
UnboundLocalError: local variable 'forecast' referenced before assignment

**Comment by DonaldPG** [comment]
Hi Dav
It looks like an error associated with incomplete stock data as input.
Here are a couple of questions to help diagnose what is happening.
1. What do you have in the PyTAAADL.params file for training and for prediction? I have it set to train using S&P500 stocks excluding those in the Naz100. For prediction, I am using Naz100. This requires building a database of stocks for both S&P500 companies, and separately for Naz100 companies. This is not explicitly stated anywhere. Sorry for that, but I created this repo to teach myself to code in python and to use deep learning convolutional neural network techniques.
stockList:                          SP_wo_Naz
stockList_predict:                  Naz100

If both of these parameters are the same (i.e., either  both SP500 or Naz100), only that stock universe is needed for both training and prediction.
BTW, even though PyTAAADL__0 is about training many deep learning networks, it validates the training using predictions on out-of-sample data.

I just updated the file PyTAAADL_update_quotes_now.py. It will now print out a summary of updated quotes like the following. This example is for updating S&P500 stock quotes. You should see similar date range and a number of symbols just above 100 or 500 depending on which index you update. Note that I have quotes stored in hdf formatted files for both Naz100 and S&P500 index member companies.
 ************************

 quote update completed.

 Date range =  1991-01-02  to  2019-07-19
 Number of symbols =  506
 shape of array holding all quotes =  (506, 7192)

 ************************

 files in symbols directory:
 -  companyNames.txt                         2.42  KB
 -  Naz100_Symbols.txt                       0.58  KB
 -  Naz100_symbolsChanges.txt                6.82  KB
 -  Naz100_Symbols_.hdf5                 5,160.05  KB
 -  Naz100_symbols__2019-07-20.txt           0.01  KB
 -  newsymbols_tempfile.txt                  2.53  KB
 -  SP500_companyNames.txt                  11.12  KB
 -  SP500_Symbols.txt                        2.53  KB
 -  SP500_symbolsChanges.txt                10.91  KB
 -  SP500_Symbols_.hdf5                 27,365.22  KB
 -  SP500_symbols__2019-07-20.txt            0.01  KB
